version: "3.6"

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    volumes:
      - "./services/users:/usr/scr/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/users_test

    depends_on:
      - db

  dlproxy:
    build:
      context: services/dlproxy
      dockerfile: Dockerfile
    volumes:
      - "./services/dlproxy:/usr/src/app"
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig


  vehicles:
    build:
      context: services/vehicles
      dockerfile: Dockerfile
    volumes:
      - "./services/vehicles:/usr/src/app"
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/users_test

    depends_on:
      - db

  stops:
    build:
      context: services/stops
      dockerfile: Dockerfile
    volumes:
      - "./services/stops:/usr/src/app"
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/users_test
    depends_on:
      - db
      - dlproxy

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    volumes:
      - "./services/db:/usr/src/app"
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  webui:
    build:
      context: ./services/Web-UI
      dockerfile: Dockerfile
    volumes:
      - "./services/Web-UI:/usr/src/app"
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig

    depends_on:
      - users
      - vehicles
      - stops
      - dlproxy